logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: xxxx  # rabbitMQ的ip地址
    port: 5672  # 端口
    username: xxxx
    password: xxxx
    virtual-host: /
    listener:
      simple:
        prefetch: 1  # 每次只能获取一条消息，处理完成才能获取下一个消息(消费慢的就不会和消费快的预取一样的消息数)